apiVersion: v2
name: harp-proxy
description: HTTP API Runtime Proxy
type: application
version: "0.1.0"
appVersion: "0.5.0b12"

dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
