apiVersion: v2
name: harp-proxy
description: HTTP API Runtime Proxy
type: application
version: "0.7.0-alpha"
appVersion: "0.7.0a1"

dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
